export const category: string
export const content: string
export const date: string
export const description: string
export const footer: string
export const hero: string
export const hero__career: string
export const hero__name: string
export const hero__photo: string
export const image: string
export const image_icon: string
export const interview: string
export const label: string
export const large: string
export const medium: string
export const small: string
export const tile: string
export const title: string
