export const highlight: string
export const highlight_guideArticleImportant: string
export const highlight_interviewBlueHighlight: string
export const highlight_interviewYellow: string
export const highlight_interviewYellowLamp: string
export const image: string
export const image_left: string
export const quote: string
export const quote__icon: string
export const quote__link: string
export const quote_guideArticleBlueQuote: string
export const quote_guideArticleQuoteWithLink: string
export const quote_interviewBlueQuote: string
export const quote_interviewWhiteQuote: string
