export const actions: string
export const back: string
export const block: string
export const button: string
export const button_black: string
export const info: string
export const settings__block: string
export const settings__blockText: string
export const settings__blockTop: string
export const settings__text: string
export const settings__title: string
export const state: string
export const state__text: string
export const state_enabled: string
export const stateButton: string
export const text: string
export const title: string
export const window: string
export const window_settings: string
