export const activeLocale: string
export const burger: string
export const burger_isOpen: string
export const content: string
export const footer: string
export const header: string
export const header__contacts: string
export const logo: string
export const menu: string
export const menu__button: string
export const menu__indent: string
export const menu__item: string
export const menu__link: string
export const menu__link_active: string
export const menu__sep: string
export const overlay: string
export const search: string
export const search__preffix: string
export const submenu: string
export const wrapper: string
