export const item: string
export const item__fullwidth: string
export const news: string
export const single: string
export const sticky: string
export const sticky__content: string
export const sticky__sidebar: string
export const sticky__sidebar_offset: string
export const themes: string
export const tiles: string
