export const block: string
export const facebook: string
export const hero: string
export const hero__about: string
export const hero__career: string
export const hero__content: string
export const hero__footer: string
export const hero__image: string
export const hero__links: string
export const hero__name: string
export const hero__photo: string
export const hero__title: string
export const info: string
export const info__date: string
export const info__sep: string
export const instagram: string
export const label: string
export const telegram: string
export const title: string
export const twitter: string
export const wrapper: string
